name: "echoform"
services:
  pubsub:
    image: valkey/valkey
    ports:
      - "6379:6379"
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: echoform
      POSTGRES_PASSWORD: echoform
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: echoform-authoritative
  backend:
    build:
      context: ../
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
      - pubsub
    environment:
      DATABASE_URL: postgresql://echoform:echoform@db:5432/echoform-authoritative
      REDIS_URL: redis://pubsub:6379
    profiles:
    - backend